"""empty message

Revision ID: 2d43cd87d385
Revises: ca3d8dd4498f
Create Date: 2023-08-21 11:44:32.412865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d43cd87d385'
down_revision = 'ca3d8dd4498f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matchparts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participants_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['participants_id'], ['participants.id'], name=op.f('fk_matchparts_participants_id_participants')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('matchparts_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_matches_participants_id_1_participants', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_matches_matchparts_id_matchparts'), 'matchparts', ['matchparts_id'], ['id'])
        batch_op.drop_column('participants_id_1')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('participants_id_1', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_matches_matchparts_id_matchparts'), type_='foreignkey')
        batch_op.create_foreign_key('fk_matches_participants_id_1_participants', 'participants', ['participants_id_1'], ['id'])
        batch_op.drop_column('matchparts_id')

    op.drop_table('matchparts')
    # ### end Alembic commands ###
