"""added second participant column

Revision ID: 37b8e7a15e4b
Revises: 845641c1cd9c
Create Date: 2023-08-18 10:43:40.323642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37b8e7a15e4b'
down_revision = '845641c1cd9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('participants_id_1', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('participants_id_2', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_matches_participants_id_participants', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_matches_participants_id_1_participants'), 'participants', ['participants_id_1'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_matches_participants_id_2_participants'), 'participants', ['participants_id_2'], ['id'])
        batch_op.drop_column('participants_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('participants_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_matches_participants_id_2_participants'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_matches_participants_id_1_participants'), type_='foreignkey')
        batch_op.create_foreign_key('fk_matches_participants_id_participants', 'participants', ['participants_id'], ['id'])
        batch_op.drop_column('participants_id_2')
        batch_op.drop_column('participants_id_1')

    # ### end Alembic commands ###
