"""added some relationship things and nullable values

Revision ID: 5834166a14a5
Revises: 65561cd4310f
Create Date: 2023-08-28 15:19:33.852246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5834166a14a5'
down_revision = '65561cd4310f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matchparts', schema=None) as batch_op:
        batch_op.alter_column('participants_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matchparts', schema=None) as batch_op:
        batch_op.alter_column('participants_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
