"""created column and relationship for match to participant

Revision ID: 65561cd4310f
Revises: 2d43cd87d385
Create Date: 2023-08-28 14:35:45.941608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65561cd4310f'
down_revision = '2d43cd87d385'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('match_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_participants_match_id_matches'), 'matches', ['match_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_participants_match_id_matches'), type_='foreignkey')
        batch_op.drop_column('match_id')

    # ### end Alembic commands ###
