"""making tables

Revision ID: 845641c1cd9c
Revises: fc001aac0507
Create Date: 2023-08-18 10:12:54.676788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '845641c1cd9c'
down_revision = 'fc001aac0507'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('picture', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tournaments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('tournament_contest', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=True),
    sa.Column('participants_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['participants_id'], ['participants.id'], name=op.f('fk_matches_participants_id_participants')),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], name=op.f('fk_matches_tournament_id_tournaments')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matches')
    op.drop_table('tournaments')
    op.drop_table('participants')
    # ### end Alembic commands ###
