"""removed null value from matchparts

Revision ID: aa6b8a4f4837
Revises: 5834166a14a5
Create Date: 2023-08-28 15:21:40.283400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa6b8a4f4837'
down_revision = '5834166a14a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matchparts', schema=None) as batch_op:
        batch_op.alter_column('participants_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matchparts', schema=None) as batch_op:
        batch_op.alter_column('participants_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
